goelp30/pulseassessment

src/app/components/common/button/button.component.html
src/app/components/common/button/button.component.spec.ts
src/app/components/common/button/button.component.ts
src/app/components/common/popup-module/popup-module.component.html
src/app/components/common/popup-module/popup-module.component.spec.ts
src/app/components/common/popup-module/popup-module.component.ts
src/app/components/common/searchbar/searchbar.component.html
src/app/components/common/searchbar/searchbar.component.spec.ts
src/app/components/common/searchbar/searchbar.component.ts
src/app/components/common/table/table.component.css
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.spec.ts
src/app/components/common/table/table.component.ts

The following changes have been completed
- Created common UI components: Reusable components such as buttons, search bar, popup-module have been implemented.
- Optimized for reusability: Components have been designed to be easily configurable and integrated across the application.

common component add - searchbar, popup-module, button

---

src/app/components/common/searchbar/searchbar.component.html
src/app/components/common/searchbar/searchbar.component.ts
src/app/components/common/table/table.component.css
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts

This pull request introduces the following changes:
1.  Replaced Search Query Parameter: Replaced search query with @input, enabling different tables to search across various query parameters.
2. Table with Searchbar: Updated the table component to include an inbuilt search bar for easier data filtering.
3. Dynamic Button Component: Implemented a reusable button component that generates buttons based on an array of objects, allowing dynamic button creation.
4. Enhanced Pagination: Improved pagination for smoother navigation and better handling of large data sets.

common table updated with common searchbar and buttons

---

src/app/components/login/login.component.css
src/app/components/login/login.component.html
src/app/components/register/register.component.css
src/app/components/register/register.component.html

Redesigned the login and Register page. 
Attached is the screenshot of the pages. 
Register Page:
Login Page:

Login and Register Page Redesign 

---

src/app/components/evaluation/evaluation-dashboard/evaluation-dashboard.component.html
src/app/components/evaluation/evaluation-dashboard/evaluation-dashboard.component.ts

Fetching User Email and user Name from Database

fetching data from database in evaluation dashboard

---

src/app/models/EvaluationAssessmentData.ts

EvaluationAssessmentData model added

Evaluation Assessment Data model added

---

src/app/app.routes.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/quiz.service.ts

Quiz model updated and changes is done according to the ask

New quiz update latest

---

src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.html
src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts

Timer added to the quiz module and timings of the questions are fetching dynamically

Dynamictimer

---

src/app/components/question/questionmodal/questionmodal.component.html
src/app/components/question/questionmodal/questionmodal.component.ts

updated remove option logic and warnings

Removeoption feature

---

src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/quiz-answer.service.ts
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html

Saving unattempted questions in database

Saving Unattempted questions in database

---

src/app/components/common/table/table.component.html
src/app/components/question/questiontable/questiontable.component.html
src/app/components/question/questiontable/questiontable.component.ts
src/app/components/subject/subjecttable/subjecttable.component.html
src/app/components/subject/subjecttable/subjecttable.component.ts

changes in the ui- all button are now using intranet button color

Updatedbutton feature

---

src/app/components/dashboard/dashboard.component.ts

dashboard icons updated

---

src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/quiz-components/submission-modal/submission-modal.component.html

quiz submission is on submmission model button

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.css
src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/question-navigator/question-navigator.component.html
src/app/components/Quiz/quiz-components/question-navigator/question-navigator.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts

minorQuizChanges

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/evaluation-dashboard/evaluation-dashboard.component.ts
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/question-display/question-display.component.spec.ts
src/app/components/evaluation/question-display/question-display.component.ts
src/app/components/evaluation/service/evaluation.service.ts
src/app/components/evaluation/view-assessment/view-assessment.component.html
src/app/components/evaluation/view-assessment/view-assessment.component.ts
src/sharedServices/FireBaseService.ts

This PR includes following changes:-
1.

Latest Changes in Evaluation Module

---

src/app/components/common/table/camel-case-to-space.pipe.ts
src/app/components/common/table/table.component.css
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/linkGeneration/Pages/assessment-records/assessment-records.component.html
src/app/components/linkGeneration/Pages/assessment-records/assessment-records.component.ts
src/app/components/linkGeneration/link-generation-modal/modal.component.html
src/app/components/linkGeneration/link-generation-modal/modal.component.ts
src/app/components/linkGeneration/link-generation/link-generation.component.html

I have correct the warning. If the user select any past time immediately  the warning will be displayed.
When the  Admin copy the link the popup will be displayed like this
Previously in drop down the names were displayed in camel casing but now they are displaying properly

Link generation model

---

src/app/components/common/button/button.component.html
src/app/components/common/button/button.component.ts
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/question/questiontable/questiontable.component.html
src/app/components/question/questiontable/questiontable.component.ts
src/app/components/subject/subjecttable/subjecttable.component.html
src/app/components/subject/subjecttable/subjecttable.component.ts
src/sharedServices/pagelabel.service.ts

-updated buttons and make header dynamic

Latestsub feature

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.css
src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.html
src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/toast.service.ts

minor changes

---

src/app/components/assessment/assess-table/assess-table.component.html
src/app/components/assessment/assess-table/assess-table.component.ts
src/app/components/assessment/assessment-list/assessment-list.component.html
src/app/components/assessment/drag-drop/drag-drop.component.css
src/app/components/assessment/drag-drop/drag-drop.component.html
src/app/components/assessment/drag-drop/drag-drop.component.ts
src/app/models/assessment.ts

in this pr i have updated back modal,reset modal ,delete modal ,edit button disabled when quiz is generated

modal updated and isLinkGenerated Added

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/question-display/question-display.component.ts
src/app/components/Quiz/quiz-components/question-navigator/question-navigator.component.ts
src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/toast.service.ts

Issue fixed for submit and option selection

minor changes is done for Quiz

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/evaluation-header/evaluation-header.component.html
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/question-display/question-display.component.ts
src/app/components/evaluation/view-assessment/view-assessment.component.css
src/app/components/evaluation/view-assessment/view-assessment.component.html
src/app/components/evaluation/view-assessment/view-assessment.component.ts

This PR Includes changes in the UI in Evaluation Module

change UI in evaluation Module

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/question-display/question-display.component.ts
src/app/components/Quiz/quiz-components/quiz-timer/quiz-timer.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.css
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/quiz-answer.service.ts
src/app/components/Quiz/services/quiz.service.ts
src/app/models/quizAnswers.ts

- Auto evaluation if no descriptive question 
- Sending Users answer for evaluation if Descriptive.
- Restrict User and giving warning if he try to refresh the page.
- Add more toastify and alert for better experience.
- Modify Completed status in assessment records.
-

Final Submission of Quiz Evaluation

---

src/app/components/common/button/button.component.html
src/app/components/common/button/button.component.ts
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/question/questiontable/questiontable.component.html
src/app/components/question/questiontable/questiontable.component.ts
src/app/components/subject/subjecttable/subjecttable.component.html
src/app/components/subject/subjecttable/subjecttable.component.ts

-moved action button to the right
-updated buttons icons
-dynamic heading for subject and questions
-icon title on hover

common changes in button icons and table alignment

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/question-display/question-display.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/quiz-components/submission-modal/submission-modal.component.html
src/app/components/Quiz/quiz-components/submission-modal/submission-modal.component.ts
src/app/components/Quiz/services/quiz-answer.service.ts
src/app/models/quizAnswers.ts

- Necessary changes in descriptive question.
- Evaluate Pass if marks percentage is higher than 70%.
- In descriptive enabled next button doesn't matted answered or not.
- Fix submission module errors
- On deselecting and selecting another options changes for backend may not be saved, Hence being resolved.
-

Major changes for quiz

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/evaluation-header/evaluation-header.component.html
src/app/components/evaluation/evaluation-header/evaluation-header.component.ts
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/view-assessment/view-assessment.component.html

Button and Fixed Errors in evaluation

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/evaluation-dashboard/evaluation-dashboard.component.ts
src/app/components/evaluation/evaluation-header/evaluation-header.component.html
src/app/components/evaluation/evaluation-header/evaluation-header.component.ts
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/question-display/question-display.component.ts
src/app/components/evaluation/service/evaluation.service.ts
src/app/components/evaluation/service/sentence-case.pipe.ts
src/app/components/evaluation/view-assessment/view-assessment.component.html
src/app/components/evaluation/view-assessment/view-assessment.component.ts

removed unnecessary comments and console.logs

---

src/app/app.routes.ts
src/app/components/Quiz/quiz-components/question-display/question-display.component.html
src/app/components/Quiz/quiz-components/question-navigator/question-navigator.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/quiz-components/submission-modal/submission-modal.component.html
src/app/components/Quiz/quiz-components/submission-modal/submission-modal.component.ts
src/app/components/Quiz/services/toast.service.ts
tailwind.config.js

advised changes has been done

---

src/app/components/common/button/button.component.html
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/common/table/text-case.pipe.ts
src/app/components/linkGeneration/Pages/assessment-records/assessment-records.component.ts
src/app/components/linkGeneration/link-generation-modal/modal.component.html

Text casing issue solved
Example:-
titlecase-> Frontend Developer
sentenceCase -> What is your name?
if you want to make any other field in titlecase/sentenceCase go to 
table.component.ts 
add your column name and casing you want in this config
columnConfig: any = {
subjectName: 'titlecase',
questionText: 'sentenceCase',
optionText: 'sentenceCase',
assessmentName: 'titlecase',
assessmentType: 'titlecase',
userName: 'titlecase',
status: 'titlecase',
};
In Records if status is completed/invalid/expired the invalid button  will be disabled

Text casing

---

src/app/components/Quiz/quiz-components/question-display/question-display.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/quiz-components/thank-you/thank-you.component.ts
src/app/components/Quiz/services/quiz.service.ts
src/app/models/assessmentRecords.ts
src/app/models/question.ts

Empty descriptive fix

---

src/app/components/assessment/assess-table/assess-table.component.html
src/app/components/assessment/assess-table/assess-table.component.ts
src/app/components/assessment/assessment-list/assessment-list.component.html
src/app/components/assessment/drag-drop/drag-drop.component.css
src/app/components/assessment/drag-drop/drag-drop.component.html
src/app/components/assessment/drag-drop/drag-drop.component.ts
src/app/components/common/popup-module/popup-module.component.html
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/subject/subjecttable/subjecttable.component.ts
src/app/models/subject.ts

Assessment left

---

src/app/components/assessment/assess-table/assess-table.component.ts
src/app/components/assessment/drag-drop/drag-drop.component.html
src/app/components/assessment/drag-drop/drag-drop.component.ts

cleaning up files

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.html
src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/question-display/question-display.component.ts

Validation added for Evaluation for Descriptive question

evaluation validation added

---

src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/quiz-components/thank-you/thank-you.component.ts
src/app/components/Quiz/services/quiz-answer.service.ts
src/app/components/question/questionmodal/questionmodal.component.ts
src/app/components/question/questiontable/questiontable.component.ts
src/app/models/question.ts
src/app/models/quizAnswers.ts

- Auto Evaluate if no Descriptive question attempted

Auto evaluation semifinal

---

src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/question/questionmodal/questionmodal.component.ts
src/app/components/question/questiontable/questiontable.component.html

show full question text on hover
update logic for all options can be correct in multi type

all options can be correct in multi type with questiontext on hover

---

src/app/app.routes.ts
src/app/components/assessment/assess-table/assess-table.component.ts
src/app/components/assessment/assessment-list/assessment-list.component.ts
src/app/components/assessment/drag-drop/drag-drop.component.html
src/app/components/assessment/drag-drop/drag-drop.component.ts
src/app/components/common/table/table.component.html
src/app/components/common/table/table.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/models/assessment.ts

Time assess

---

src/app/components/Quiz/terms-conditions/terms-conditions.component.html

Updated terms and conditions

---

src/app/components/common/table/table.component.html

title on hover only on questiontext

title on hover only on questiontext

---

src/app/components/evaluation/evaluate-assessment/evaluate-assessment.component.ts
src/app/components/evaluation/evaluation-header/evaluation-header.component.html
src/app/components/evaluation/evaluation-header/evaluation-header.component.ts
src/app/components/evaluation/question-display/question-display.component.html
src/app/components/evaluation/question-display/question-display.component.ts

UI changed and Logic changed for multiple questions

---

src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/quiz-answer.service.ts
src/app/components/question/questionmodal/questionmodal.component.ts
src/app/components/question/questiontable/questiontable.component.ts
src/app/models/question.ts
src/app/models/quizAnswers.ts

- Auto Evaluation for Non Descriptive question Attempted.

Necessary update done for Auto Evaluation

---

src/app/components/Quiz/quiz-components/auto-submission-modal/auto-submission-modal.component.html
src/app/components/Quiz/quiz-components/auto-submission-modal/auto-submission-modal.component.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.html
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/services/quiz.service.ts

- Random funtion changed as per the requirement
- Auto submission model added

Auto submission final

---

src/app/app.routes.ts
src/app/components/Quiz/auth/link-status.guard.ts
src/app/components/Quiz/quiz-components/quiz/quiz.component.ts
src/app/components/Quiz/terms-conditions/terms-conditions.component.ts
src/app/components/linkGeneration/Pages/assessment-records/assessment-records.component.ts
src/app/components/linkGeneration/link-generation-modal/modal.component.ts
src/app/models/assessmentRecords.ts

Multilple links can be created for single user for same Assessment

Multilple links can be created for single user for same Assessment
